version: '2'

services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: sample
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  fastapi-app:
    image: fastapi_app_mahda
    environment:
      MB_DB_DBNAME: postgres
      MB_DB_HOST: postgres-db
      MB_DB_PASS: admin
      MB_DB_PORT: 5432
      MB_DB_TYPE: postgres
      MB_DB_USER: postgres
    ports:
      - "5004:5000"
    depends_on:
      - postgres-db

volumes:
  pg-data: